version: "3.7"

services:
  database:
    image: postgres
    container_name: database_teste
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=teste
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: teste
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata:
    driver: local

